name: Build Linux Desktop

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    name: Build shapez Linux x64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg



      - name: Install Yarn dependencies
        run: |
          yarn
          cd gulp/
          yarn
          cd ..

      - name: Build Linux desktop app
        run: |
          cd gulp
          yarn gulp bundle.standalone-steam.all

      - name: Upload Linux build
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: shapez-linux-x64
          path: build_output/

      - name: Wait 3 minutes
        run: sleep 180

      - name: Delete artifact
        env:
          GH_TOKEN: ${{ github.token }}
          ARTIFACT_ID: ${{ steps.upload.outputs.artifact-id }}
        run: |
          gh api \
            --method DELETE \
            "/repos/${{ github.repository }}/actions/artifacts/${ARTIFACT_ID}"
